### PR TITLE
Fixed for latest markdown library

### PR DESCRIPTION
**Pull request by Dzordzu**

### CODE REVIEW

**Comment by jordan-bucholtz** [comment]
Looks good to me, I had to make a similar fix locally. Hopefully this is merged soon.

**Comment by jcfr** [comment]
Thanks @Dzordzu for submitting the fix :pray: 

@ryanfox When you have a chance, let us know if anything else is required to move forward with the integration.

**Comment by jcfr** [comment]
@ryanfox To provide some more context, here is improved commit message you could consider:

```
Fix documentation build due to breaking change in markdown

This commit workarounds backward incompatible change introduced in
Markdown 3.4 through Python-Markdown/markdown@659a43659 (Update th/td
to use style attribute)

It addresses error like the following:

  Extension error (sphinx_markdown_tables):
  Handler <function process_tables at 0x7f12fd69dc20> for event 'source-read' threw an exception (exception: __init__() missing 1 required positional argument: 'config')

See https://github.com/ryanfox/sphinx-markdown-tables/issues/36
and https://python-markdown.github.io/change_log/release-3.4/
```

**Comment by ryanfox** [comment]
Thank you for the fix, everyone.

**Pull request merged**
